/* prettier-ignore-start */
/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOGENERATED. DO NOT EDIT.
 *
 * To regenerate, run `npx convex dev`.
 *
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as accounts from "../accounts";
import type * as budgets from "../budgets";
import type * as categories from "../categories";
import type * as savingsGoals from "../savingsGoals";
import type * as transactions from "../transactions";
import type * as users from "../users";
import type * as aiQueries from "../aiQueries";
import type * as aiInsights from "../aiInsights";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * @typeParam Module - The module containing the function.
 * @typeParam FunctionName - The name of the function.
 */
type AnyFunction = FunctionReference<any, "public" | "internal", any, any, any, any, any, any>;

type ApiFromModules<Modules extends Record<string, Record<string, AnyFunction>>> =
  FilterApi<
    {
      [ModuleName in keyof Modules]: {
        [FunctionName in keyof Modules[ModuleName]]: Modules[ModuleName][FunctionName];
      };
    },
    FunctionReference<any, "public" | "internal", any, any, any, any, any, any>
  >;

/**
 * A utility for type-checking Convex functions.
 *
 * @public
 */
export type Api = ApiFromModules<{
  accounts: typeof accounts;
  budgets: typeof budgets;
  categories: typeof categories;
  savingsGoals: typeof savingsGoals;
  transactions: typeof transactions;
  users: typeof users;
  aiQueries: typeof aiQueries;
  aiInsights: typeof aiInsights;
}>;

export type FunctionReference<
  ArgsValidator,
  Visibility extends "public" | "internal",
  ReturnType,
  Args,
  Output,
  Route,
  CatchAll,
  Middleware
> = any;

/* prettier-ignore-end */

