/* prettier-ignore-start */
/* eslint-disable */
/**
 * Generated `dataModel` utility.
 *
 * THIS CODE IS AUTOGENERATED. DO NOT EDIT.
 *
 * To regenerate, run `npx convex dev`.
 *
 * @module
 */

import type { DataModelFromSchemaDefinition } from "convex/server";
import type { GenericId } from "convex/values";
import schema from "../schema";

/**
 * The names of all of your Convex tables.
 */
export type TableNames = string;

/**
 * The type of a document stored in Convex.
 */
export type Document = {
  _id: GenericId<TableNames>;
  _creationTime: number;
  [key: string]: any;
};

/**
 * An `Id` is a typed wrapper around a string that represents the ID of a
 * document in Convex.
 */
export type Id<TableName extends TableNames> = GenericId<TableName>;

/**
 * A type representing your Convex data model.
 *
 * This type includes information about what tables you have, the type of
 * documents stored in those tables, and the indexes defined on them.
 *
 * This type is used to provide better autocomplete and error messages.
 *
 * @public
 */
export type DataModel = DataModelFromSchemaDefinition<typeof schema>;

/* prettier-ignore-end */

