/* prettier-ignore-start */
/* eslint-disable */
/**
 * Generated server utility.
 *
 * THIS CODE IS AUTOGENERATED. DO NOT EDIT.
 *
 * To regenerate, run `npx convex dev`.
 *
 * @module
 */

import type {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
  CronJobsForAPI,
  FunctionReference,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  GenericDatabaseReader,
  GenericDatabaseWriter,
  DataModelFromSchemaDefinition,
  DocumentByInfo,
  Document,
  Id,
  TableNames,
  Value,
  WithoutSystemFields,
} from "convex/server";
import type { GenericId } from "convex/values";
import type { DataModel } from "./dataModel";

export type {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
  CronJobsForAPI,
  FunctionReference,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  GenericDatabaseReader,
  GenericDatabaseWriter,
  DataModelFromSchemaDefinition,
  DocumentByInfo,
  Document,
  Id,
  TableNames,
  Value,
  WithoutSystemFields,
};

export type DataModel = typeof DataModel;
export type TableNames = keyof DataModel;
export type Doc<TableName extends TableNames> = DataModel[TableName]["document"];
export type Id<TableName extends TableNames> = GenericId<TableName>;

/* prettier-ignore-end */

